# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('art', models.ImageField(blank=True, null=True, upload_to='music/media/album-art')),
                ('credits', models.TextField(blank=True, default='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('bandcamp', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('art', models.ImageField(blank=True, null=True, upload_to='music/media/outfit-art')),
                ('bandcamp', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20)),
                ('audio', models.FileField(upload_to=music.models.album_directory_path)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Outfit'),
        ),
    ]
