# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['pub_date']},
        ),
    ]
